### ISSUE TITLE
would we able to change the custom error code instead of `FORBIDDEN`

### ISSUE THREAD

**Issue by jspantheonlab** [AstrumU/graphql-authz#102]
I tried adding rules with the custom GraphqlError, but the response throw the correct error message but with wrong `error.extensions.code`.

**Comment by DavidTkachenkoAstrumu** [comment]
@jspantheonlab, the `FORBIDDEN` message comes from `authz` default `processError` handler. You cannot modify it, but you can provide your own `processError` implementation.

Just pass it as part of your `IAuthZConfig` configuration params:

```
function ownErrorHandler(error: unknown): never {
  // Do whatever you wish e.g. just rethrow:
  throw error
}

// With the apollo plugin
authZApolloPlugin({ rules: authZRules, processError: ownErrorHandler });

// Or envelop
authZEnvelopPlugin({ rules: authZRules, processError: ownErrorHandler });
```
