### ISSUE TITLE
GiraphQL compatibility

### ISSUE THREAD

**Issue by hayes** [AstrumU/graphql-authz#55]
Hey,

Just wrote a tiny plugin for GiraphQL that makes applying rules to fields/types slightly simpler when building schemas with giraphql. https://giraphql.com/plugins/authz

Obviously not necessary to make things work, but gets you something with better type-checking and avoids needing to define a complicated extensions object for each field/type.

**Comment by dimatill** [comment]
Hey @hayes ,

This is great! I'll check it later today and add a link into README

**Comment by dimatill** [comment]
@hayes I've just merged README updates https://github.com/AstrumU/graphql-authz/pull/59
Feel free to create PR you have some suggestions

Is there anything else I can help with? 😇
