### ISSUE TITLE
Queries for __typename fail

### ISSUE THREAD

**Issue by hayes** [AstrumU/graphql-authz#56]
When using `wrapExecuteFn` queries that contain `__typename` will fail with an error `Cannot read property 'args' of undefined`.

This comes from https://github.com/AstrumU/graphql-authz/blob/main/packages/core/src/rules-compiler.ts#L285-L287

the `__typename` field is not actually a field in the graphql schema, so certain operations (like trying to get the field schema, or fetch args for it) will not work.

**Comment by dimatill** [comment]
@hayes thank you for opening the issue! 🙏 Would you like to create PR for fixing this?
