### ISSUE TITLE
@graphql-authz/directive and @graphql 16 have conflicting dependencies

### ISSUE THREAD

**Issue by emiwidp** [AstrumU/graphql-authz#85]
@graphql-authz/directive@1.1.3, it in turns references @graphql-tools/utils@"8.1.2, which again in turn is conflicting with graphql@16.

It would be good to update the @graphql-tools/utils dependency to a later version to resolve these conflicts.

**Comment by DavidTkachenkoAstrumu** [comment]
The issue was resolved in https://github.com/AstrumU/graphql-authz/pull/114 by bumping to version `10.0.11`.

Please update to `@graphql-authz/directive@1.1.4`.
